### ISSUE TITLE
Protocolo de Manchester

### ISSUE THREAD

**Issue by kyriosdata** [kyriosdata/profiling#7]
Define nível de gravidade de paciente:
- vermelho (emergência)
- laranja (muito urgente)
- amarelo (urgente)
- verde (pouco urgente)
- azul (não urgente)

Crie um ConceptMap que mapeia as cores para os códigos correspondentes: emergencia, muito-urgente, urgente, pouco-urgente e nao-urgente. Ou seja, devem ser criadas duas instâncias de CodeSystem, uma para cada sistema de codificação (cores e termos), e outras duas instâncias de ValueSet, uma para cada CodeSystem definido. 

Subir estas quatro instâncias para o hapi.fhir.org/baseR4 (servidor de teste do HAPI FHIR) e executar a operação $translate, por exemplo, para obter emergencia (destino) quando o código vermelho (origem) for fornecido.

**Comment by nogueiralegacy** [comment]
- Instâncias Criadas

[codesystemCor.fsh.json](https://github.com/kyriosdata/profiling/files/13358428/codesystemCor.fsh.json)
[codesystemTexto.fsh.json](https://github.com/kyriosdata/profiling/files/13358429/codesystemTexto.fsh.json)
[conceptMap.fsh.json](https://github.com/kyriosdata/profiling/files/13358430/conceptMap.fsh.json)
[valuesetCor.fsh.json](https://github.com/kyriosdata/profiling/files/13358431/valuesetCor.fsh.json)
[valuesetTexto.fsh.json](https://github.com/kyriosdata/profiling/files/13358432/valuesetTexto.fsh.json)

- Testadas no servidor HAPI-FHIR

Requisição:
GET
url:
 `{{server}}/ConceptMap/$translate?url=http://example.com/ConceptMapCorTexto&code=vermelho&system=http://example.com/CodeSystemProtocoloManchesterCor`

Resposta do servidor:
[response.json](https://github.com/kyriosdata/profiling/files/13358442/response.json)

**Comment by kyriosdata** [comment]
@nogueiralegacy  Criar pull request no qual os arquivos em FSH são depositados no diretório **terminologias**. Não é preciso fornecer os arquivos em JSON.

**Comment by nogueiralegacy** [comment]
#9 Pull request solicitado @kyriosdata
