### ISSUE TITLE
Processo de validação via instância do servidor HAPI FHIR

### ISSUE THREAD

**Issue by kyriosdata** [kyriosdata/profiling#8]
## Validação usando servidor HAPI FHIR
Definir processo no qual o servidor FHIR é empregado localmente para validação de artefatos de conformidade.

Deve incluir: 

- Passo (comando) para baixar o servidor.
- Comando para iniciar o servidor.
- Comandos para subir os artefatos de conformidade.
- Comando para validar os artefatos de exemplo no servidor iniciado localmente.

** Resultado esperado

- Sequência de passos que realiza as operações citadas acima. Esta sequência pode ser documentada aqui mesmo na issue. 
- Você deve estar fluente para executar estes passos normalmente. Assuma que o computador possui Java e outras ferramentas necessárias. 
- Esta sequência deve ser realizada com sucesso para o conteúdo do diretório **adaptacoes**.

**Comment by nogueiralegacy** [comment]
# Processo de Validação
## Descrição
Este documento tem o propósto de esclarecer o processo de validação de instância FHIR por meio do servidor HAPI-FHIR local.

## Pré-requisitos
- GIT
- JDK 17
- Maven

## Passo a passo
### Baixar o servidor
Abra o prompt e selecione um diretório a sua escolha e execute o seguinte comando:  
`git clone https://github.com/hapifhir/hapi-fhir-jpaserver-starter`

### Iniciar o servidor
Execute o seguinte comando entrar no diretório onde o servidor foi baixado:  
`cd hapi-fhir-jpaserver-starter`  
Execute o seguinte comando para iniciar o servidor:  
`mvn jetty:run`

### Inserir artefatos de conformidade
Realizar requisições HTTP para a API FHIR do servidor iniciado:

- Operação: POST
- Body: instância a ser inserida
- URL: {base}/{resourceType}

{base}: a base da API do servidor escolhido.   
{resourceType}: o tipo de instância a ser inserida.

**No caso do servidor local a {base} padrão é http://localhost:8080/fhir**

Exemplo:
![exemplo_servidor_inserir](https://github.com/kyriosdata/profiling/assets/80354850/82c186b3-fb23-48cf-a222-af54d3e4cf2e)


### Para validar artefatos:
Realizar requisições HTTP para a API FHIR do servidor iniciado:  
- Operação: POST
- Body: instância a ser validada
- URL: {base}/{resourceType}/$validate

{base}: a base da API do servidor escolhido.  
{resourceType}: o tipo de instância a ser validada.

**No caso do servidor local a {base} padrão é http://localhost:8080/fhir**

Exemplo:
![exemplo_servidor_validar](https://github.com/kyriosdata/profiling/assets/80354850/6d6916a5-9594-4708-81a5-0b5a4bbf12a5)



**Os artefatos enviados ao servidor devem estar em um dos seguintes formatos: JSON, XML ou Turtle.**

**Comment by nogueiralegacy** [comment]
@kyriosdata realizei as operações de validação e inserção para boa parte dos artefatos no diretório adaptação, mas não todos.

**Comment by kyriosdata** [comment]
@nogueiralegacy precisamos de exemplos, sequências como aquelas acima, que demandam o uso de ValueSet, CodeSystem, perfil e só então a validação de instância de exemplo. Ou seja, pelo menos 4 atividades para uma validação completa. Usando postman, conforme está fazendo, a sequência seria extensa, mas também vale.
